Fix OpenWrt 25 not installing some virtual packages
For example, `ddns-scripts` depends on virtual package `ip`, but neither
`ip-full` nor `ip-tiny` get installed:

```
$ cat result/*.manifest | grep '^ip' # no output
$ nix log result/ | grep ip-
( 42/149) Installing ip-tiny (6.18.0-r2)
ERROR: ip-tiny-6.18.0-r2: package mentioned in index not found (try 'apk update')
```

The problem is only 1 real package(ip-full) is added to `packages/` dir,
OpenWrt 24 works fine with this, but OpenWrt 25 does not after switching
to `apk`.

This commit fixes the virtual package `depends` calculation, before allPackages.ip is:

```
{
  depends = [ "ip-full" ];
  type = "virtual";
}
```

After:
```
{
  depends = [ "ip-full" "ip-tiny" ];
  type = "virtual";
}
```